DEVICE_PATH := device/fairphone/fp3

# Architecture
TARGET_ARCH 			:= arm64
TARGET_ARCH_VARIANT 	:= armv8-a
TARGET_CPU_ABI 			:= arm64-v8a
TARGET_CPU_ABI2 		:=
TARGET_CPU_VARIANT 		:= cortex-a53
TARGET_CPU_VARIANT_RUNTIME := kryo

TARGET_2ND_ARCH 		:= arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI 		:= armeabi-v7a
TARGET_2ND_CPU_ABI2 	:= armeabi
TARGET_2ND_CPU_VARIANT 	:= cortex-a53
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a53

# Platform
BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_USES_QCOM_HARDWARE   	:= true
TARGET_BOARD_PLATFORM     	:= msm8953
TARGET_BOARD_PLATFORM_GPU  	:= qcom-adreno506

# Bootloader stuff
TARGET_USES_UEFI := true
TARGET_BOOTLOADER_BOARD_NAME := FP3

# Kernel
TARGET_PREBUILT_KERNEL     := $(DEVICE_PATH)/prebuilt/Image.gz-dtb
TARGET_KERNEL_ARCH         := $(TARGET_ARCH)
TARGET_KERNEL_HEADER_ARCH  := $(TARGET_ARCH)
TARGET_KERNEL_VERSION 	   := 4.9

BOARD_KERNEL_BASE          := 0x80000000
BOARD_KERNEL_PAGESIZE      := 2048
BOARD_KERNEL_OFFSET        := 0x00008000
BOARD_KERNEL_TAGS_OFFSET   := 0x00000100
BOARD_RAMDISK_OFFSET       := 0x01000000
BOARD_KERNEL_IMAGE_NAME    := Image.gz-dtb
BOARD_BOOT_HEADER_VERSION  := 0

BOARD_MKBOOTIMG_ARGS  += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS  += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS  += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS  += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS  += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS  += --pagesize $(BOARD_KERNEL_PAGESIZE)

BOARD_KERNEL_CMDLINE := \
	androidboot.hardware=qcom \
	androidboot.boot_devices=soc/7824900.sdhci \
	androidboot.bootdevice=7824900.sdhci \
	androidboot.selinux=permissive \
	androidboot.usbconfigfs=true \
	androidboot.mode=recovery

BOARD_KERNEL_CMDLINE += \
	ehci-hcd.park=3 \
	lpm_levels.sleep_disabled=1 \
	msm_rtb.filter=0x237 \
	firmware_class.path=/vendor/firmware_mnt/image \
	loop.max_part=7 \
	msm_poweroff.download_mode=0 \
	panic=-1

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

BOARD_AVB_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_SYSTEM_ROLLBACK_INDEX := 0
BOARD_AVB_SYSTEM_ROLLBACK_INDEX_LOCATION := 2

# Allow for building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_USES_NETWORK := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true

# Partitions
BOARD_FLASH_BLOCK_SIZE			:= 131072
BOARD_BOOTIMAGE_PARTITION_SIZE 	:= 67108864
BOARD_DTBOIMG_PARTITION_SIZE 	:= 8388608
BOARD_USERDATAIMAGE_PARTITION_SIZE  := 52335451136

BOARD_VENDORIMAGE_PARTITION_SIZE	:= 1073741824
BOARD_SYSTEMIMAGE_PARTITION_SIZE	:= 3221225472

# Filesystems
TARGET_USERIMAGES_USE_EXT4  := true
TARGET_USERIMAGES_USE_F2FS  := true
TARGET_USES_MKE2FS          := true

# Recovery
TARGET_SYSTEM_PROP := \
    $(DEVICE_PATH)/system.prop

TARGET_RECOVERY_FSTAB := \
    $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_RECOVERY_QCOM_RTC_FIX := true

# Debugging
TARGET_USES_LOGD := true
